name: Push to organization
on: workflow_dispatch

jobs:
  push-to-organization:
    runs-on: ubuntu-20.04
    steps:
      - name: Push to organization
        uses: 5G00BD88-3006-Innovaatioprojekti/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'output'
          destination-github-username: '5G00BD88-3006-Innovaatioprojekti'
          destination-repository-name: 'Nelilaskin-Testi'
          user-email: testi@testi.com
          target-branch: main
